create type "public"."status" as enum ('public', 'private', 'nonpublic');

create type "public"."subjects" as enum ('physics', 'chemistry', 'biology', 'hygiene', 'pharmacology', 'pharmacy', 'pathology', 'legal', 'ethics', 'practice');

create table "public"."examdata" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "exam_year" integer,
    "grade" smallint,
    "subject" subjects,
    "problem_statement" text,
    "problem_img" text,
    "choices" jsonb,
    "choices_img" jsonb,
    "correct" smallint,
    "explanation" text,
    "status" status
);


alter table "public"."examdata" enable row level security;

CREATE UNIQUE INDEX a_pkey ON public.examdata USING btree (id);

alter table "public"."examdata" add constraint "a_pkey" PRIMARY KEY using index "a_pkey";

grant delete on table "public"."examdata" to "anon";

grant insert on table "public"."examdata" to "anon";

grant references on table "public"."examdata" to "anon";

grant select on table "public"."examdata" to "anon";

grant trigger on table "public"."examdata" to "anon";

grant truncate on table "public"."examdata" to "anon";

grant update on table "public"."examdata" to "anon";

grant delete on table "public"."examdata" to "authenticated";

grant insert on table "public"."examdata" to "authenticated";

grant references on table "public"."examdata" to "authenticated";

grant select on table "public"."examdata" to "authenticated";

grant trigger on table "public"."examdata" to "authenticated";

grant truncate on table "public"."examdata" to "authenticated";

grant update on table "public"."examdata" to "authenticated";

grant delete on table "public"."examdata" to "service_role";

grant insert on table "public"."examdata" to "service_role";

grant references on table "public"."examdata" to "service_role";

grant select on table "public"."examdata" to "service_role";

grant trigger on table "public"."examdata" to "service_role";

grant truncate on table "public"."examdata" to "service_role";

grant update on table "public"."examdata" to "service_role";

create policy "Enable read access for all users"
on "public"."examdata"
as permissive
for select
to public
using (true);




